version: "3.9"

services:
  docusaurus:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./giscus.json:/app/giscus.json
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock

      - ./blog:/app/blog
      - ./pages:/app/pages
      - ./src:/app/src
      - ./static:/app/static