version: "3"

services:
  docusaurus:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./blog:/app/blog
      - ./giscus.json:/app/giscus.json
      - ./package.json:/app/package.json
      - ./pages:/app/pages
      - ./src:/app/src
      - ./static:/app/static
    working_dir: /app
