version: "3.9"

services:
  docusaurus:
    build: .
    ports:
      - 3000:3000
    volumes:
      # - ./giscus.json:/app/giscus.json
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock

      - ./.devcontainer:/app/.devcontainer
      - ./docusaurus.config.js:/app/docusaurus.config.js
      - ./blog:/app/blog
      - ./src:/app/src
      - ./static:/app/static