"""
Syntax validation engine for code generated by the AI.

This module provides a lightweight way to verify that the code produced by the
LLM is at least syntactically correct before displaying it to the user.
"""

import ast
import subprocess
from pathlib import Path
from typing import Final


class CodeValidator:
    """Performs syntax checks for various programming languages."""

    @staticmethod
    def is_valid_python(code: str) -> bool:
        """
        Checks for valid Python syntax using the Abstract Syntax Tree (AST).
        This is a safe and fast method that doesn't execute any code.
        """
        try:
            ast.parse(code)
            return True
        except SyntaxError:
            return False

    @staticmethod
    def is_valid_php(code: str) -> bool:
        """
        Checks for valid PHP syntax by calling `php -l`.
        Requires the 'php' executable to be in the system's PATH.
        """
        try:
            # The 'php -l' command reads from stdin, which is ideal.
            process: Final[subprocess.CompletedProcess[str]] = subprocess.run(
                ["php", "-l"],
                input=code,
                capture_output=True,
                text=True,
                check=False,
            )
            # A successful lint returns 0 and outputs "No syntax errors".
            return process.returncode == 0 and "No syntax errors" in process.stdout
        except FileNotFoundError:
            # If PHP is not installed, we cannot validate, so we skip.
            return True

    @staticmethod
    def is_valid_bash(code: str) -> bool:
        """
        Checks for valid Bash/sh syntax by calling `bash -n`.
        Requires 'bash' to be in the system's PATH.
        """
        try:
            # The 'bash -n' command checks syntax without executing.
            process: Final[subprocess.CompletedProcess[str]] = subprocess.run(
                ["bash", "-n"],
                input=code,
                capture_output=True,
                text=True,
                check=False,
            )
            # A return code of 0 means the syntax is valid.
            return process.returncode == 0
        except FileNotFoundError:
            # If Bash is not installed, skip the check.
            return True

    @classmethod
    def validate(cls, code: str, filename: str) -> bool:
        """
        Validates code syntax based on the file extension.
        Returns True if syntax is valid or if the language is not supported.
        """
        extension: Final[str] = Path(filename).suffix
        match extension:
            case ".py":
                return cls.is_valid_python(code)
            case ".php":
                return cls.is_valid_php(code)
            case ".sh":
                return cls.is_valid_bash(code)
            case _:
                # For other languages (yaml, json, etc.), we skip validation.
                return True
