name: my_sample

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_HOME: ${APP_HOME:-/app}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.13}
        TIMEZONE: ${TIMEZONE:-Europe/Brussels}
    image: my_sample_prod:latest
    container_name: app
    env_file: .env
    ports:
      - "8000:8000"
    user: "1001:1001"
    security_opt:
      - no-new-privileges:true
