project:
  type: website

website:
  title: "Simple Brand Example"
  navbar:
    title: "Demo CO"
    tools:
      - icon: github
        href: https://github.com/quarto-dev/quarto-examples/tree/main/brand/brand-simple