# cspell:ignore dood,groupid,johndoe
name: "dood-as-unprivileged"
services:
  dood:
    build:
      args:
        - DOCKER_OS_GROUPID=${DOCKER_OS_GROUPID:-1000}
        - DOCKER_OS_USERID=${DOCKER_OS_USERID:-1000}
        - DOCKER_OS_USERNAME=${DOCKER_OS_USERNAME:-johndoe}
    user: "${DOCKER_OS_USERID:-1000}:${DOCKER_OS_GROUPID:-1000}"
    tty: true
    // highlight-next-line
    group_add:
      // highlight-next-line
      - ${DOCKER_GROUPID:-1001}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
