php-cs-fixer: vendor update-them
	@echo "And finally run php-cs-fixer"
    vendor/bin/php-cs-fixer

vendor:
	@echo "First get vendors"

update-them:
	@echo "Then update vendors"
	exit 2 && echo "Oups, an error has occurred"
