// highlight-next-line
name: %%name=kingsbridge%%
services:
  joomla:
    // highlight-next-line
    container_name: %%name=kingsbridge%%-app
    [...]

  joomladb:
    // highlight-next-line
    container_name: %%name=kingsbridge%%-db
    [...]
