import type { JSX } from "react";
import Layout from "@theme/Layout";
import Link from "@docusaurus/Link";
import FollowFeed from "@site/src/components/FollowFeed";
import { getBlogMetadata } from "@site/src/components/Blog/utils/posts";
import { createSlug } from "@site/src/components/Blog/utils/slug";
import { getTagLabel } from "@site/src/data/tags";
import styles from "./follow.module.css";

/**
 * "Follow this blog" — the one page that explains what a feed is and lists every
 * feed the build produces: the site-wide one in three formats, one per series
 * and one per tag (written by plugins/blog-feed-plugin).
 *
 * It exists so the pedagogy lives in a single place: the FollowFeed blocks
 * scattered on articles, tag pages and series pages link here instead of each
 * repeating "here is what an RSS reader is".
 *
 * The lists are derived from the same front matter the feed plugin groups on,
 * so a new tag or series shows up here without anyone editing this file.
 */
export default function FollowPage(): JSX.Element {
  const posts = getBlogMetadata();

  const seriesEntries = new Map<string, { label: string; count: number }>();
  const tagEntries = new Map<string, { label: string; count: number }>();

  for (const post of posts) {
    if (post.series) {
      const slug = createSlug(post.series);
      const entry = seriesEntries.get(slug);
      if (entry) entry.count += 1;
      else seriesEntries.set(slug, { label: post.series, count: 1 });
    }

    // mainTag is folded in alongside tags, exactly as the feed plugin does it —
    // a post's main tag is not always repeated in its `tags` list.
    const seen = new Set<string>();
    for (const tag of [...post.tags, post.mainTag]) {
      if (!tag) continue;
      const value = typeof tag === "string" ? tag : tag.label;
      const slug = createSlug(value);
      if (!slug || seen.has(slug)) continue;
      seen.add(slug);

      const entry = tagEntries.get(slug);
      if (entry) entry.count += 1;
      else tagEntries.set(slug, { label: getTagLabel(value), count: 1 });
    }
  }

  const byLabel = (a: [string, { label: string }], b: [string, { label: string }]) =>
    a[1].label.localeCompare(b[1].label);

  const seriesList = [...seriesEntries.entries()].sort(byLabel);
  const tagList = [...tagEntries.entries()].sort(byLabel);

  return (
    <Layout
      title="Follow this blog"
      description="Every RSS feed published by this blog: the whole blog, one per series, one per tag."
    >
      <div className="container margin-top--lg margin-bottom--xl">
        <h1>Follow this blog</h1>

        <p className={styles.lede}>
          No newsletter, no account, no tracking: this blog publishes{" "}
          <strong>feeds</strong>. You paste a URL into a feed reader once, and new posts
          show up there on their own — a little like a mailbox you own, except nobody gets
          your address.
        </p>

        <FollowFeed feedUrl="/blog/rss.xml" label="every new post" />

        <h2>Never used a feed reader?</h2>
        <p>
          Pick one, paste a URL from this page into it, done. The popular hosted ones are{" "}
          <a href="https://feedly.com" target="_blank" rel="noopener noreferrer">
            Feedly
          </a>{" "}
          and{" "}
          <a href="https://www.inoreader.com" target="_blank" rel="noopener noreferrer">
            Inoreader
          </a>{" "}
          (both free to start, both work in a browser). On the desktop,{" "}
          <a href="https://netnewswire.com" target="_blank" rel="noopener noreferrer">
            NetNewsWire
          </a>{" "}
          and Thunderbird read feeds too. Any of them will do — the URLs below are
          standard.
        </p>

        <h2>The whole blog</h2>
        <p>
          Three formats of the same thing. Take RSS unless your reader asks for something
          else; the Atom and JSON ones are generated by Docusaurus and carry summaries
          only.
        </p>
        {/*
          Plain <a>, not Docusaurus's <Link>: these are static files written into
          the build output, not registered routes, so <Link> would hand them to
          the client-side router and find nothing. Same reasoning as the "View
          raw" link in CopyAsMarkdown and the Markdown link on a series page.
        */}
        <ul className={styles.formatList}>
          <li>
            <a href="/blog/rss.xml" target="_blank" rel="noopener noreferrer">
              <code>/blog/rss.xml</code>
            </a>{" "}
            — RSS 2.0, with the full text of each post
          </li>
          <li>
            <a href="/blog/atom.xml" target="_blank" rel="noopener noreferrer">
              <code>/blog/atom.xml</code>
            </a>{" "}
            — Atom
          </li>
          <li>
            <a href="/blog/feed.json" target="_blank" rel="noopener noreferrer">
              <code>/blog/feed.json</code>
            </a>{" "}
            — JSON Feed
          </li>
        </ul>
        <p className={styles.formatNote}>
          Opening the RSS one in a browser shows a readable page rather than raw markup —
          it carries an XSLT stylesheet. Atom and JSON have none, so those two will look
          like what they are.
        </p>

        <h2>One series at a time</h2>
        <p>
          The most useful ones, honestly: a series feed tells you when the next episode of
          something you are already reading lands, and nothing else.
        </p>
        <ul className={styles.feedList}>
          {seriesList.map(([slug, { label, count }]) => (
            <li key={slug}>
              <Link to={`/series/${slug}`}>{label}</Link>{" "}
              <span className={styles.count}>({count})</span>{" "}
              <a href={`/series/${slug}/rss.xml`} className={styles.feedLink}>
                feed
              </a>
            </li>
          ))}
        </ul>

        <h2>One topic at a time</h2>
        <p>
          Every tag has its own feed. Follow <code>docker</code> and you will not hear
          about Outlook VBA.
        </p>
        <ul className={styles.feedList}>
          {tagList.map(([slug, { label, count }]) => (
            <li key={slug}>
              <Link to={`/blog/tags/${slug}`}>{label}</Link>{" "}
              <span className={styles.count}>({count})</span>{" "}
              <a href={`/blog/tags/${slug}/rss.xml`} className={styles.feedLink}>
                feed
              </a>
            </li>
          ))}
        </ul>
      </div>
    </Layout>
  );
}
