server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;
}

server {
    listen 443 ssl;
    listen [::]:443;

    server_name localhost;

    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    root /usr/share/nginx/html;
 }
