# syntax=docker/dockerfile:1
FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y \
        curl \
        wget \
        git \
        python3 \
        python3-pip \
        build-essential \
        python3-dev \
        libssl-dev \
        pkg-config && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip3 install flask requests numpy pandas scikit-learn --break-system-packages

RUN mkdir /app

COPY app.py /app/

WORKDIR /app

CMD ["python3", "app.py"]
