SHELL:=bash

default: help

COLOR_YELLOW:=33

# highlight-next-line
.PHONY: help
# highlight-next-line
help: ## Show the help with the list of commands
    # highlight-next-line
 @clear
    # highlight-next-line
 @awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n\n"} /^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[0;33m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)
    # highlight-next-line
 @echo ""
