#!/usr/bin/env node
/**
 * Batch-refreshes the tags-review journal (.todos/0000-tags-review-journal.md) by calling
 * suggest-tags.mjs (Ollama) for every article under blog/ and .unpublished/ that isn't
 * already tracked there with a fresh suggestion.
 *
 * This script only ever writes the journal — never an article's frontmatter. Applying a
 * decision is `tags set-tags <file> <tag1,tag2,...>` (.scripts/tags-manager.py), done from a
 * Claude Code session that walks the journal's pending rows with the author (see CLAUDE.md,
 * "Auto-memory" / the freshness & reader-review journals this one mirrors).
 *
 * A row is left untouched on a normal run once it exists — regardless of its Revu state —
 * so re-running this doesn't re-spend an Ollama call per article every time. It IS
 * regenerated when:
 *   - the article is new (no row yet),
 *   - blog/tags.yml changed since the last run (a hash is stamped in the journal header —
 *     new tags may now apply to already-reviewed articles too),
 *   - `--force` is passed (regenerate everything), or
 *   - a specific `<article>` is named (regenerate just that one row).
 *
 * Usage:
 *   node scripts/tags-review.mjs                 # new + never-generated articles only
 *   node scripts/tags-review.mjs --force          # regenerate every article's suggestion
 *   node scripts/tags-review.mjs <article>        # regenerate just one article's row
 *   node scripts/tags-review.mjs --status         # print pending rows, no Ollama calls
 *
 * In the devcontainer: `tags review [--force] [<article>]`, `tags review --status`.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { findPosts, parseFrontMatter } from "./lib/blog-corpus.mjs";
import { hashSource } from "./lib/eli5-hash.mjs";
import { suggestTags } from "./suggest-tags.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "..");
const JOURNAL_PATH = path.join(projectRoot, ".todos", "0000-tags-review-journal.md");
const TAGS_YML_PATH = path.join(projectRoot, "blog", "tags.yml");

const C = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  dim: "\x1b[2m",
  red: "\x1b[1;31m",
  green: "\x1b[1;32m",
  yellow: "\x1b[1;33m",
  cyan: "\x1b[1;36m",
};

const HEADER = [
  "# Tags Review Journal",
  "",
  "Tracks which articles' `tags` frontmatter has been checked against `blog/tags.yml` with",
  "`scripts/suggest-tags.mjs` (Ollama). Generated by `tags review` (see",
  ".devcontainer/scripts/interactive.sh); the **Revu** column is filled in by Claude during a",
  "review session with the author, after applying (or deliberately keeping) a row's",
  "suggestion via `tags set-tags`. Do not edit the table by hand — a decision belongs",
  "in the Revu/Notes columns, not in a text editor.",
  "",
  "Articles with no gap (the model confirms every tag already set) are marked `auto` and",
  "never need a look. A row is regenerated the next time `tags review` runs whenever",
  "`blog/tags.yml` changed since — new tags may now apply — or with `--force`.",
].join("\n");

// ── Journal I/O ──────────────────────────────────────────────────────────────

function splitRow(line) {
  return line
    .trim()
    .replace(/^\|/, "")
    .replace(/\|$/, "")
    .split("|")
    .map((cell) => cell.trim());
}

function splitCell(cell) {
  return cell === "—" || cell === "" ? [] : cell.split(",").map((t) => t.trim());
}

/** Reads the journal's current rows (keyed by slug) and its stamped tags.yml hash, if any. */
function parseJournal() {
  if (!fs.existsSync(JOURNAL_PATH)) return { hash: null, rows: new Map() };

  const raw = fs.readFileSync(JOURNAL_PATH, "utf-8");
  const hashMatch = raw.match(/<!--\s*tags-yml-hash:\s*([a-f0-9]+)\s*-->/);
  const rows = new Map();

  for (const line of raw.split(/\r?\n/)) {
    if (!line.startsWith("|") || line.startsWith("| ----") || line.startsWith("| Revu")) {
      continue;
    }

    const [revu, slug, state, current, toAdd, toRemove, notes] = splitRow(line);
    if (!slug) continue;

    rows.set(slug, {
      revu: revu === "—" ? null : revu,
      slug,
      state,
      currentTags: splitCell(current),
      toAdd: splitCell(toAdd),
      toRemove: splitCell(toRemove),
      notes: notes === "—" ? "" : notes,
    });
  }

  return { hash: hashMatch ? hashMatch[1] : null, rows };
}

const formatCell = (list) => (list.length > 0 ? list.join(", ") : "—");

function writeJournal(rows, tagsYmlHash) {
  const lines = [
    HEADER,
    `<!-- tags-yml-hash: ${tagsYmlHash} -->`,
    "",
    "| Revu | Slug | État | Tags actuels | À ajouter | À retirer | Notes |",
    "| ---- | ---- | ---- | ------------ | --------- | --------- | ----- |",
  ];

  for (const row of rows) {
    lines.push(
      `| ${row.revu ?? "—"} | ${row.slug} | ${row.state} | ${formatCell(row.currentTags)} | ${formatCell(row.toAdd)} | ${formatCell(row.toRemove)} | ${row.notes || "—"} |`,
    );
  }

  fs.mkdirSync(path.dirname(JOURNAL_PATH), { recursive: true });
  fs.writeFileSync(JOURNAL_PATH, lines.join("\n") + "\n");
}

// ── Corpus ───────────────────────────────────────────────────────────────────

/** `.unpublished/` is a draft by construction; `blog/` honors its own `draft` flag. */
function articleState(file, data) {
  if (file.includes(`${path.sep}.unpublished${path.sep}`)) return "unpublished";
  return data.draft === true || data.draft === "true" ? "draft" : "published";
}

function loadCorpus() {
  const roots = [path.join(projectRoot, "blog")];
  const unpublishedDir = path.join(projectRoot, ".unpublished");
  if (fs.existsSync(unpublishedDir)) roots.push(unpublishedDir);

  const files = roots.flatMap((root) => findPosts(root)).sort();
  const posts = [];

  for (const file of files) {
    const raw = fs.readFileSync(file, "utf-8");
    const { data } = parseFrontMatter(raw);
    if (!data.title) continue;

    posts.push({
      file,
      rel: path.relative(projectRoot, file),
      slug: data.slug || path.basename(path.dirname(file)),
      state: articleState(file, data),
    });
  }

  return posts;
}

// ── Suggestion → row ─────────────────────────────────────────────────────────

async function generateRow(post) {
  const { existingTags, missing, unrecognized } = await suggestTags(post.file);
  const toAdd = missing.map((t) => t.slug);
  const toRemove = unrecognized;
  const hasDelta = toAdd.length > 0 || toRemove.length > 0;

  return {
    revu: hasDelta ? null : new Date().toISOString().slice(0, 10),
    slug: post.slug,
    state: post.state,
    currentTags: existingTags,
    toAdd,
    toRemove,
    notes: hasDelta ? "" : "auto — rien à changer",
  };
}

// ── Status (read-only) ───────────────────────────────────────────────────────

function printStatus(rows) {
  const all = [...rows.values()];

  if (all.length === 0) {
    console.log(
      `\n${C.yellow}No journal yet.${C.reset} Run ${C.bold}tags review${C.reset} to generate one.\n`,
    );
    return;
  }

  const pending = all.filter((r) => !r.revu);
  const reviewed = all.filter((r) => r.revu);

  console.log(
    `\n${C.bold}Tags review — status${C.reset}  ${C.dim}(${all.length} article(s) tracked)${C.reset}`,
  );
  console.log(`  ${C.green}${reviewed.length}${C.reset} revu(s)`);
  console.log(`  ${C.bold}${pending.length}${C.reset} à traiter\n`);

  for (const row of pending) {
    console.log(`${C.cyan}${row.slug}${C.reset} ${C.dim}(${row.state})${C.reset}`);
    if (row.toAdd.length > 0)
      console.log(`  ${C.green}+ ${row.toAdd.join(", ")}${C.reset}`);
    if (row.toRemove.length > 0)
      console.log(`  ${C.red}- ${row.toRemove.join(", ")}${C.reset}`);
  }
  console.log("");
}

// ── CLI ──────────────────────────────────────────────────────────────────────

async function run() {
  const args = process.argv.slice(2);

  if (args.includes("--help") || args.includes("-h")) {
    console.log(`
Usage:
  node scripts/tags-review.mjs                 # new + never-generated articles only
  node scripts/tags-review.mjs --force         # regenerate every article's suggestion
  node scripts/tags-review.mjs <article>       # regenerate just one article's row (path or slug)
  node scripts/tags-review.mjs --status        # print the journal's pending rows, no Ollama calls

Journal: .todos/0000-tags-review-journal.md — the Revu column is filled in by Claude during
a review session with the author, not by this script.
`);
    return;
  }

  const { hash: storedHash, rows: existingRows } = parseJournal();

  if (args.includes("--status")) {
    printStatus(existingRows);
    return;
  }

  const force = args.includes("--force");
  const target = args.find((a) => !a.startsWith("--"));

  const posts = loadCorpus();

  if (target) {
    const matches = posts.filter((p) => p.rel.includes(target) || p.slug === target);
    if (matches.length === 0) {
      console.error(`No article matches "${target}".`);
      process.exitCode = 1;
      return;
    }
    if (matches.length > 1) {
      console.error(`Ambiguous — "${target}" matches ${matches.length} articles:`);
      for (const m of matches) console.error(`  ${m.rel}`);
      process.exitCode = 1;
      return;
    }
  }

  const tagsYmlHash = hashSource(fs.readFileSync(TAGS_YML_PATH, "utf-8"));
  const tagsYmlChanged = storedHash !== null && storedHash !== tagsYmlHash;

  if (tagsYmlChanged) {
    console.log(
      `${C.yellow}blog/tags.yml changed since the last run — refreshing every article.${C.reset}`,
    );
  }
  if (target && existingRows.size === 0) {
    console.log(
      `${C.yellow}No journal yet — this first run generates the full corpus, not just "${target}".${C.reset}`,
    );
  }

  const resultRows = [];
  const freshSlugs = [];

  // Every row is flushed to disk as soon as it's known — an interrupted run (Ctrl+C, a
  // crashed Ollama call, a killed process) on a ~300-article corpus must not lose the
  // articles already processed, same principle as questions-review.mjs's per-mutation save.
  for (const [index, post] of posts.entries()) {
    const existing = existingRows.get(post.slug);
    const isTarget =
      Boolean(target) && (post.rel.includes(target) || post.slug === target);
    const needsGen = force || tagsYmlChanged || !existing || isTarget;

    if (!needsGen) {
      resultRows.push(existing);
      continue;
    }

    process.stdout.write(
      `\r${C.dim}[${index + 1}/${posts.length}]${C.reset} ${post.rel}${" ".repeat(30)}`,
    );

    try {
      const row = await generateRow(post);
      resultRows.push(row);
      freshSlugs.push(row);
    } catch (err) {
      console.error(`\n${C.red}Error on ${post.rel}: ${err.message}${C.reset}`);
      if (existing) resultRows.push(existing);
    }

    writeJournal(resultRows, tagsYmlHash);
  }

  if (freshSlugs.length > 0) process.stdout.write("\n");

  writeJournal(resultRows, tagsYmlHash);

  const pending = resultRows.filter((r) => !r.revu);
  const autoConfirmed = freshSlugs.filter((r) => r.revu !== null).length;

  console.log(`\n${C.bold}Journal updated:${C.reset} .todos/0000-tags-review-journal.md`);
  console.log(
    `  ${resultRows.length} article(s) total, ${freshSlugs.length} regenerated this run (${autoConfirmed} auto-confirmed).`,
  );
  console.log(`  ${C.bold}${pending.length}${C.reset} article(s) need a look.\n`);
}

run().catch((err) => {
  console.error(`${C.red}❌ Error:${C.reset}`, err.message);
  process.exitCode = 1;
});
