import React, { useMemo } from "react";
import { generateSeriesList } from "@site/src/components/Blog/utils/series";
import Translate from "@docusaurus/Translate";
import PostCard from "@site/src/components/Blog/PostCard";
import styles from "./styles.module.css";

/**
 * SeriesCards component
 *
 * Renders a responsive grid of blog article series using metadata generated by `generateSeriesList`.
 * Each card displays the series title, image, and a summary of published and draft articles.
 * Cards link to a dedicated page for each series.
 *
 * Layout:
 * - Uses Docusaurus Infima grid classes (`row`, `col--4`) for responsive layout.
 * - Falls back to a friendly message if no series are found.
 *
 * Dependencies:
 * - `generateSeriesList` (utility to group and format blog posts by series)
 * - `PostCard` (component to render individual series cards)
 *
 * Location: src/components/SeriesCards/index.js
 */

const DEFAULT_IMAGE = "/img/default.webp";

/**
 * Safely imports the series data and returns it, or an empty array if the import fails.
 * This prevents the application from crashing if the data file is missing.
 * @returns {Array} The series data or an empty array.
 */
function getSeriesData() {
  try {
    const data = require("@site/src/data/series.js");
    return data?.default ?? data;
  } catch (error) {
    return [];
  }
}

const SERIES_DATA = getSeriesData();

export default function SeriesCards() {
  const seriesList = generateSeriesList();

  const enriched = useMemo(() => seriesList.map((serie) => {
    const data = SERIES_DATA.find((s) => s.name === serie.seriesName);

    let imagePath = data?.image ?? DEFAULT_IMAGE;

    return {
      ...serie,
      counter: data?.counter ?? serie.counter,
      description: data?.description ?? serie.description,
      image: imagePath,
      title: data?.title ?? serie.title,
    };
  }), [seriesList]);

  if (enriched.length === 0) {
    return (
      <div className="text--center margin-vert--xl">
        <h2>
          <Translate id="blog.seriesCards.noSeries">No article series found</Translate>
        </h2>
      </div>
    );
  }

  return (
    <div className="container margin-top--lg margin-bottom--lg">
      <div className={styles.seriesGrid}>
        {enriched.map((serie) => (
          <PostCard key={serie.permalink} post={serie} />
        ))}
      </div>
    </div>
  );
}
