import { generateSeriesList } from "@site/src/components/Blog/utils/series";
import PostCard from "@site/src/components/Blog/PostCard";

/**
 * SeriesCards component
 *
 * Renders a responsive grid of blog article series using metadata generated by `generateSeriesList`.
 * Each card displays the series title, image, and a summary of published and draft articles.
 * Cards link to a dedicated page for each series.
 *
 * Layout:
 * - Uses Docusaurus Infima grid classes (`row`, `col--4`) for responsive layout.
 * - Falls back to a friendly message if no series are found.
 *
 * Dependencies:
 * - `generateSeriesList` (utility to group and format blog posts by series)
 * - `PostCard` (component to render individual series cards)
 *
 * Location: src/components/SeriesCards/index.js
 */

export default function SeriesCards() {
  const seriesList = generateSeriesList();

  if (seriesList.length === 0) {
    return (
      <div className="text--center margin-vert--xl">
        <h2>No article series found</h2>
      </div>
    );
  }

  return (
    <div className="container margin-top--lg margin-bottom--lg">
      <div className="row">
        {seriesList.map((serie) => (
          <PostCard post={serie} />
        ))}
      </div>
    </div>
  );
}
