import { generateSeriesList } from "@site/src/components/Blog/utils/series";
import PostCard from "@site/src/components/Blog/PostCard";
import styles from "./styles.module.css";

/**
 * SeriesCards component
 *
 * Renders a responsive grid of blog article series using metadata generated by `generateSeriesList`.
 * Each card displays the series title, image, and a summary of published and draft articles.
 * Cards link to a dedicated page for each series.
 *
 * Layout:
 * - Uses Docusaurus Infima grid classes (`row`, `col--4`) for responsive layout.
 * - Falls back to a friendly message if no series are found.
 *
 * Dependencies:
 * - `generateSeriesList` (utility to group and format blog posts by series)
 * - `PostCard` (component to render individual series cards)
 *
 * Location: src/components/SeriesCards/index.js
 */

import SERIES_DATA from "../../../data/series.js";

const DEFAULT_IMAGE = "/img/default.webp";

export default function SeriesCards() {
  const seriesList = generateSeriesList();

  const enriched = seriesList.map((serie) => {
    const data = SERIES_DATA.find((s) => s.name === serie.seriesName);

    let imagePath = data?.image ?? DEFAULT_IMAGE;

    return {
      ...serie,
      counter: data?.counter ?? serie.counter,
      description: data?.description ?? serie.description,
      image: imagePath,
      title: data?.title ?? serie.title,
    };
  });

  if (enriched.length === 0) {
    return (
      <div className="text--center margin-vert--xl">
        <h2>No article series found</h2>
      </div>
    );
  }

  return (
    <div className="container margin-top--lg margin-bottom--lg">
      <div className={styles.seriesGrid}>
        {enriched.map((serie) => (
          <PostCard key={serie.permalink} post={serie} />
        ))}
      </div>
    </div>
  );
}
