name: demo

services:

  %%name=counter%%:
    build: .
    container_name: %%name=counter%%
    image: demo/counter
    # highlight-next-line
    volumes:
      # highlight-next-line
      - ./data:/data
