// Auto-generated by scripts/precompile-handlebars.mjs — do not edit by hand.
// Source: ssh_config_template raw string. Regenerate after any template change.
export const sshConfigTemplate = {"0":function(container,depth0,helpers,partials,data) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "# 1. Bastion — no ProxyJump, no IdentityFile\nHost "
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"vmIp") || (depth0 != null ? lookupProperty(depth0,"vmIp") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vmIp","hash":{},"data":data,"loc":{"start":{"line":2,"column":5},"end":{"line":2,"column":13}}}) : helper))) != null ? stack1 : "")
    + "\n    User "
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"vmUser") || (depth0 != null ? lookupProperty(depth0,"vmUser") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vmUser","hash":{},"data":data,"loc":{"start":{"line":3,"column":9},"end":{"line":3,"column":19}}}) : helper))) != null ? stack1 : "")
    + "\n\n";
},"1":function(container,depth0,helpers,partials,data,blockParams,depths) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return ((stack1 = lookupProperty(helpers,"if").call(alias1,(data && lookupProperty(data,"first")),{"name":"if","hash":{},"fn":container.program(2, data, 0, blockParams, depths),"inverse":container.noop,"data":data,"loc":{"start":{"line":5,"column":24},"end":{"line":6,"column":7}}})) != null ? stack1 : "")
    + "Host "
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"domain") || (depth0 != null ? lookupProperty(depth0,"domain") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"domain","hash":{},"data":data,"loc":{"start":{"line":6,"column":12},"end":{"line":6,"column":22}}}) : helper))) != null ? stack1 : "")
    + "\n    User "
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"user") || (depth0 != null ? lookupProperty(depth0,"user") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"user","hash":{},"data":data,"loc":{"start":{"line":7,"column":9},"end":{"line":7,"column":17}}}) : helper))) != null ? stack1 : "")
    + "\n";
},"2":function(container,depth0,helpers,partials,data,blockParams,depths) {
    var stack1, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "# "
    + ((stack1 = lookupProperty(helpers,"if").call(depth0 != null ? depth0 : (container.nullContext || {}),(depths[1] != null ? lookupProperty(depths[1],"vmIp") : depths[1]),{"name":"if","hash":{},"fn":container.program(3, data, 0, blockParams, depths),"inverse":container.program(4, data, 0, blockParams, depths),"data":data,"loc":{"start":{"line":5,"column":40},"end":{"line":5,"column":72}}})) != null ? stack1 : "")
    + ". Domain defaults — in effect when connecting via full FQDN only\n";
},"3":function(container,depth0,helpers,partials,data) {
    return "2";
},"4":function(container,depth0,helpers,partials,data) {
    return "1";
},"5":function(container,depth0,helpers,partials,data) {
    return "3";
},"6":function(container,depth0,helpers,partials,data) {
    var stack1, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return ((stack1 = lookupProperty(helpers,"if").call(depth0 != null ? depth0 : (container.nullContext || {}),(depth0 != null ? lookupProperty(depth0,"domains") : depth0),{"name":"if","hash":{},"fn":container.program(3, data, 0),"inverse":container.program(4, data, 0),"data":data,"loc":{"start":{"line":8,"column":32},"end":{"line":8,"column":64}}})) != null ? stack1 : "");
},"7":function(container,depth0,helpers,partials,data,blockParams,depths) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "Host "
    + ((stack1 = (lookupProperty(helpers,"lower")||(depth0 && lookupProperty(depth0,"lower"))||alias2).call(alias1,(depths[1] != null ? lookupProperty(depths[1],"projectName") : depths[1]),{"name":"lower","hash":{},"data":data,"loc":{"start":{"line":10,"column":5},"end":{"line":10,"column":29}}})) != null ? stack1 : "")
    + "_"
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"environment") || (depth0 != null ? lookupProperty(depth0,"environment") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"environment","hash":{},"data":data,"loc":{"start":{"line":10,"column":30},"end":{"line":10,"column":45}}}) : helper))) != null ? stack1 : "")
    + "_app\n    RequestTTY yes\n    RemoteCommand sudo -u "
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"appUser") || (depth0 != null ? lookupProperty(depth0,"appUser") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"appUser","hash":{},"data":data,"loc":{"start":{"line":12,"column":26},"end":{"line":12,"column":37}}}) : helper))) != null ? stack1 : "")
    + " bash -c \"cd "
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"appDir") || (depth0 != null ? lookupProperty(depth0,"appDir") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"appDir","hash":{},"data":data,"loc":{"start":{"line":12,"column":50},"end":{"line":12,"column":60}}}) : helper))) != null ? stack1 : "")
    + " && exec bash -l\"\n\nHost "
    + ((stack1 = (lookupProperty(helpers,"lower")||(depth0 && lookupProperty(depth0,"lower"))||alias2).call(alias1,(depths[1] != null ? lookupProperty(depths[1],"projectName") : depths[1]),{"name":"lower","hash":{},"data":data,"loc":{"start":{"line":14,"column":5},"end":{"line":14,"column":29}}})) != null ? stack1 : "")
    + "_"
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"environment") || (depth0 != null ? lookupProperty(depth0,"environment") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"environment","hash":{},"data":data,"loc":{"start":{"line":14,"column":30},"end":{"line":14,"column":45}}}) : helper))) != null ? stack1 : "")
    + " "
    + ((stack1 = (lookupProperty(helpers,"lower")||(depth0 && lookupProperty(depth0,"lower"))||alias2).call(alias1,(depths[1] != null ? lookupProperty(depths[1],"projectName") : depths[1]),{"name":"lower","hash":{},"data":data,"loc":{"start":{"line":14,"column":46},"end":{"line":14,"column":70}}})) != null ? stack1 : "")
    + "_"
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"environment") || (depth0 != null ? lookupProperty(depth0,"environment") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"environment","hash":{},"data":data,"loc":{"start":{"line":14,"column":71},"end":{"line":14,"column":86}}}) : helper))) != null ? stack1 : "")
    + "_app\n    HostName "
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"hostname") || (depth0 != null ? lookupProperty(depth0,"hostname") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hostname","hash":{},"data":data,"loc":{"start":{"line":15,"column":13},"end":{"line":15,"column":25}}}) : helper))) != null ? stack1 : "")
    + "\n    User "
    + ((stack1 = (lookupProperty(helpers,"globLookup")||(depth0 && lookupProperty(depth0,"globLookup"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"hostname") : depth0),(depths[1] != null ? lookupProperty(depths[1],"domains") : depths[1]),"domain","user",(depths[1] != null ? lookupProperty(depths[1],"userB") : depths[1]),{"name":"globLookup","hash":{},"data":data,"loc":{"start":{"line":16,"column":9},"end":{"line":16,"column":68}}})) != null ? stack1 : "")
    + "\n\n";
},"8":function(container,depth0,helpers,partials,data) {
    return "4";
},"9":function(container,depth0,helpers,partials,data,blockParams,depths) {
    var stack1, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return ((stack1 = lookupProperty(helpers,"if").call(depth0 != null ? depth0 : (container.nullContext || {}),(depth0 != null ? lookupProperty(depth0,"domains") : depth0),{"name":"if","hash":{},"fn":container.program(5, data, 0, blockParams, depths),"inverse":container.program(3, data, 0, blockParams, depths),"data":data,"loc":{"start":{"line":18,"column":32},"end":{"line":18,"column":64}}})) != null ? stack1 : "");
},"10":function(container,depth0,helpers,partials,data) {
    return "every host except the bastion";
},"11":function(container,depth0,helpers,partials,data) {
    return "every host";
},"12":function(container,depth0,helpers,partials,data) {
    var stack1, helper, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return " !"
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"vmIp") || (depth0 != null ? lookupProperty(depth0,"vmIp") : depth0)) != null ? helper : container.hooks.helperMissing),(typeof helper === "function" ? helper.call(depth0 != null ? depth0 : (container.nullContext || {}),{"name":"vmIp","hash":{},"data":data,"loc":{"start":{"line":19,"column":20},"end":{"line":19,"column":28}}}) : helper))) != null ? stack1 : "");
},"13":function(container,depth0,helpers,partials,data) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "    ProxyJump "
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"vmUser") || (depth0 != null ? lookupProperty(depth0,"vmUser") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vmUser","hash":{},"data":data,"loc":{"start":{"line":20,"column":26},"end":{"line":20,"column":36}}}) : helper))) != null ? stack1 : "")
    + "@"
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"vmIp") || (depth0 != null ? lookupProperty(depth0,"vmIp") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vmIp","hash":{},"data":data,"loc":{"start":{"line":20,"column":37},"end":{"line":20,"column":45}}}) : helper))) != null ? stack1 : "")
    + "\n";
},"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data,blockParams,depths) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return ((stack1 = lookupProperty(helpers,"if").call(alias1,(depth0 != null ? lookupProperty(depth0,"vmIp") : depth0),{"name":"if","hash":{},"fn":container.program(0, data, 0, blockParams, depths),"inverse":container.noop,"data":data,"loc":{"start":{"line":1,"column":0},"end":{"line":5,"column":7}}})) != null ? stack1 : "")
    + ((stack1 = lookupProperty(helpers,"each").call(alias1,(depth0 != null ? lookupProperty(depth0,"domains") : depth0),{"name":"each","hash":{},"fn":container.program(1, data, 0, blockParams, depths),"inverse":container.noop,"data":data,"loc":{"start":{"line":5,"column":7},"end":{"line":8,"column":9}}})) != null ? stack1 : "")
    + "# "
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,(depth0 != null ? lookupProperty(depth0,"vmIp") : depth0),{"name":"if","hash":{},"fn":container.program(5, data, 0, blockParams, depths),"inverse":container.program(6, data, 0, blockParams, depths),"data":data,"loc":{"start":{"line":8,"column":11},"end":{"line":8,"column":71}}})) != null ? stack1 : "")
    + ". Short aliases\n"
    + ((stack1 = lookupProperty(helpers,"each").call(alias1,(depth0 != null ? lookupProperty(depth0,"servers") : depth0),{"name":"each","hash":{},"fn":container.program(7, data, 0, blockParams, depths),"inverse":container.noop,"data":data,"loc":{"start":{"line":9,"column":0},"end":{"line":18,"column":9}}})) != null ? stack1 : "")
    + "# "
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,(depth0 != null ? lookupProperty(depth0,"vmIp") : depth0),{"name":"if","hash":{},"fn":container.program(8, data, 0, blockParams, depths),"inverse":container.program(9, data, 0, blockParams, depths),"data":data,"loc":{"start":{"line":18,"column":11},"end":{"line":18,"column":71}}})) != null ? stack1 : "")
    + ". Global defaults — fallback for "
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,(depth0 != null ? lookupProperty(depth0,"vmIp") : depth0),{"name":"if","hash":{},"fn":container.program(10, data, 0, blockParams, depths),"inverse":container.program(11, data, 0, blockParams, depths),"data":data,"loc":{"start":{"line":18,"column":104},"end":{"line":18,"column":170}}})) != null ? stack1 : "")
    + "\nHost *"
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,(depth0 != null ? lookupProperty(depth0,"vmIp") : depth0),{"name":"if","hash":{},"fn":container.program(12, data, 0, blockParams, depths),"inverse":container.noop,"data":data,"loc":{"start":{"line":19,"column":6},"end":{"line":19,"column":35}}})) != null ? stack1 : "")
    + "\n"
    + ((stack1 = lookupProperty(helpers,"if").call(alias1,(depth0 != null ? lookupProperty(depth0,"vmIp") : depth0),{"name":"if","hash":{},"fn":container.program(13, data, 0, blockParams, depths),"inverse":container.noop,"data":data,"loc":{"start":{"line":20,"column":0},"end":{"line":21,"column":7}}})) != null ? stack1 : "")
    + "    IdentityFile ~/.ssh/"
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"sshKey") || (depth0 != null ? lookupProperty(depth0,"sshKey") : depth0)) != null ? helper : container.hooks.helperMissing),(typeof helper === "function" ? helper.call(alias1,{"name":"sshKey","hash":{},"data":data,"loc":{"start":{"line":21,"column":31},"end":{"line":21,"column":41}}}) : helper))) != null ? stack1 : "")
    + "\n\n    # Optional — prevent silently-dropped idle connections\n    ServerAliveInterval 30\n    ServerAliveCountMax 3";
},"useData":true,"useDepths":true};
